install.packages(setdiff("pacman", rownames(installed.packages())))
pacman::p_load(ncdf4)
pacman::p_load(raster)
pacman::p_load(rasterVis)
pacman::p_load(gridExtra)
pacman::p_load(tidyverse)
pacman::p_load(ggpubr)
pacman::p_load(spBayes)
pacman::p_load(gstat)
pacman::p_load(rgdal)
pacman::p_load(rgeos)
pacman::p_load(devtools)
if (!"VoCC" %in% rownames(installed.packages())) {
  devtools::install_github("JorGarMol/VoCC", dependencies = TRUE, build_vignettes = FALSE)
}
pacman::p_load(VoCC)
pacman::p_load(jpeg)
pacman::p_load(ggmcmc)
pacman::p_load(forecast)
pacman::p_load(sf) 
pacman::p_load(elevatr) 
pacman::p_load(coda) 
devtools::install_github("usa-npn/rnpn")
pacman::p_load(rnpn) 
pacman::p_load(mapproj)
