install.packages(setdiff("pacman", rownames(installed.packages())))
pacman::p_load(forecast)
pacman::p_load(ggmcmc)
pacman::p_load(ggpubr)
pacman::p_load(gridExtra)
pacman::p_load(gstat)
pacman::p_load(jpeg)
pacman::p_load(ncdf4)
pacman::p_load(raster)
pacman::p_load(rasterVis)
pacman::p_load(rgdal)
pacman::p_load(sf)
pacman::p_load(spBayes)
pacman::p_load(tidyverse)
pacman::p_load(VoCC)

